### ISSUE TITLE
Links to the dataset are broken

### ISSUE THREAD

**Issue by fbottarel** [mvandermerwe/PointSDF#2]
As the name suggests. @mvandermerwe the links in the README to download the raw and processed dataset are broken, would you please look into it? It should be an easy fix. 

Thanks!

**Comment by martinmatak** [comment]
@fbottarel They work for me, although you need to sign up to box.com to obtain the data (it can be done via Google account) 
The only thing is that links in the readme are swapped (i.e. raw data is linked as processed data and the other way around @mvandermerwe )

@fbottarel if you share a link where I could upload the data, I can download it and reupload it there

**Comment by fbottarel** [comment]
Links were fixed a while back. I forgot to close the issue!
