### ISSUE TITLE
Regarding running the pretrained model

### ISSUE THREAD

**Issue by submagr** [mvandermerwe/PointSDF#6]
Dear @mvandermerwe,
Thanks for providing the dataset and model checkpoint files. However, I am having a hard time figuring out which one is the trained model path inside [the drive link](https://drive.google.com/drive/u/0/folders/1x_rXjnE2F7iemyIX_TWA0AyRvhCo8eT3) you added recently.

Inside the run_sdf_model.py file, it seems like you are [loading the model from model_path / model.ckpt](https://github.com/mvandermerwe/PointSDF/blob/master/run_sdf_model.py#L78). However, I am unable to locate any file named "model.ckpt" inside the drive. 

It will be great if you can provide some assistance.

Thanks in advance.

**Comment by mvandermerwe** [comment]
Try using the data stored in `pointconv_mse.tar.gz` in the drive. Unzip the file somewhere and point the path to `model.ckpt` in this folder. If I remember correctly, the tensorflow `Saver` object should identify the correct load file.

Let me know if this works!

**Comment by submagr** [comment]
Hi Mark, Thanks. I was able to run your pre-trained models.

For others, instructions in [rakeshv24 fork](https://github.com/rakeshv24/PointSDF) were very useful.
