### ISSUE TITLE
Regarding shape completion inference time of ~1 minute

### ISSUE THREAD

**Issue by submagr** [mvandermerwe/PointSDF#7]
HI @mvandermerwe,
I am observing shape completion inference time in the ballpark of 1 minute on GPU. I am not 100% sure that the average planning time reported in the paper includes the shape completion time or not.

![Screenshot from 2021-08-28 20-27-33](https://user-images.githubusercontent.com/12503665/131234272-7d800a6c-1ea0-4cdf-a378-361c17a88a61.png)

Can you please confirm? If not, can you please provide us a rough estimate of what this shape completion inference time should be?

Thanks!

**Comment by mvandermerwe** [comment]
Hi @submagr,

This timing result does _not_ include the time for a full shape completion. As highlighted in the paper, our methodology actually doesn't recover the explicit geometry but maintains the object as an implicit SDF, querying at points of interest (i.e., points on the robot). This avoids having to reconstruct the full object, saving time and avoiding discretization errors in the resulting geometry. See Eq. 7 in our paper for details.

If you are looking for a reconstruction of the object, that is, if reconstruction is the final goal, then an implicit representation like PointSDF inherently requires many queries to the network, thus we must usually run the network many many times (hence the observed shape completion time). To attempt to make things more efficient, we have an implementation of the Multiresolution IsoSurface Extraction (MISE) algorithm, introduced by [Mescheder et al.](https://openaccess.thecvf.com/content_CVPR_2019/html/Mescheder_Occupancy_Networks_Learning_3D_Reconstruction_in_Function_Space_CVPR_2019_paper.html). Without this, we would require many more passes through the network to reach a similar resolution extraction. You can see the above linked paper for further discussion and additional ways to improve the mesh quality we didn't implement (such as using surface gradients to smooth the mesh further).
